services:
  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
        - 1433:1433
    environment:
        SA_PASSWORD: "P@ssw0rd"
        ACCEPT_EULA: "Y"

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080