version: "3"
services:
  mssql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: mssql
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: "P@ssw0rd"
      ACCEPT_EULA: "Y"

  mysql:
    image: mysql
    container_name: mysql
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080